import { AgreementDocumentsViewModel, AgreementGeneralViewModel, PayerSidebarProfile } from './agent-rules-widget.model';

export const AGREEMENT_GENERAL_DEMO: AgreementGeneralViewModel = {
    providerName: 'CM-UCE',
    providerDisplayName: 'Centro Médico UCE',
    agreementBadge: 'MASTER AGREEMENT',
    contractId: 'CONV-ARS-PRIMERA-2024',
    payer: 'ARS Primera',
    planName: 'Plan de Salud Unificado',
    legalRepresentative: 'Dr. Carlos Méndez',
    contractType: 'Evento',
    effectiveFrom: '2024-01-01',
    effectiveTo: '2024-12-31',
    jurisdiction: 'República Dominicana',
    capitationBase: 45000,
    capitationCurrency: 'DOP',
    capitationPeriod: 'mo',
    budgetTotal: 7000000000,
    billedYtd: 4500000000,
    pendingApproval: 500000000,
    budgetCurrency: 'DOP',
};

export const DEMO_CONTRACT_DOCUMENT = {
    repositoryId: 'default',
    repositoryNodeId: '07b0dd64-d021-4795-821e-f45d857956b4',
    title: 'Contrato de Prestación de Servicios',
    mimeType: 'application/pdf',
};

export const AGREEMENT_DOCUMENTS_DEMO: AgreementDocumentsViewModel = {
    primaryDocument: {
        title: DEMO_CONTRACT_DOCUMENT.title,
        status: 'Active',
        contractId: AGREEMENT_GENERAL_DEMO.contractId,
        expiresAt: AGREEMENT_GENERAL_DEMO.effectiveTo,
        repositoryId: DEMO_CONTRACT_DOCUMENT.repositoryId,
        repositoryNodeId: DEMO_CONTRACT_DOCUMENT.repositoryNodeId,
        mimeType: DEMO_CONTRACT_DOCUMENT.mimeType,
    },
    relatedFiles: [
        {
            id: 'annex-1',
            title: 'Lista maestra de precios v2',
            category: 'TECHNICAL_ANNEXES',
            sizeLabel: '2.4 MB',
            updatedAt: '2024-09-01',
        },
        {
            id: 'annex-2',
            title: 'Definiciones SLA',
            category: 'TECHNICAL_ANNEXES',
            sizeLabel: '890 KB',
            updatedAt: '2024-06-15',
        },
    ],
    historicalVersions: [{ id: 'hist-1', title: 'Convenio archivado v1', archivedAt: '2023-10-12' }],
};

const SURa_GENERAL: AgreementGeneralViewModel = {
    providerName: 'Sura ARL',
    providerDisplayName: 'Sura ARL Nacional',
    agreementBadge: 'DRAFT AGREEMENT',
    contractId: 'AGR-2024-SURA-0012',
    payer: 'Sura ARL Nacional',
    planName: 'Plan Riesgos Laborales',
    legalRepresentative: 'Ana Ramírez P.',
    contractType: 'Capitación',
    effectiveFrom: '2024-03-01',
    effectiveTo: '2025-02-28',
    jurisdiction: 'Bogotá D.C., Cundinamarca',
    capitationBase: 38000,
    capitationCurrency: 'COP',
    capitationPeriod: 'mo',
    budgetTotal: 5200000000,
    billedYtd: 2100000000,
    pendingApproval: 320000000,
    budgetCurrency: 'COP',
};

const NUEVA_EPS_GENERAL: AgreementGeneralViewModel = {
    providerName: 'Nueva EPS',
    providerDisplayName: 'Nueva EPS Integral',
    agreementBadge: 'MASTER AGREEMENT',
    contractId: 'AGR-2024-NEPS-0088',
    payer: 'Nueva EPS Integral',
    planName: 'Plan Integral de Salud',
    legalRepresentative: 'Juan Pablo Díaz',
    contractType: 'Evento',
    effectiveFrom: '2023-06-01',
    effectiveTo: '2025-06-30',
    jurisdiction: 'Medellín, Antioquia',
    capitationBase: 42000,
    capitationCurrency: 'COP',
    capitationPeriod: 'mo',
    budgetTotal: 6100000000,
    billedYtd: 3900000000,
    pendingApproval: 410000000,
    budgetCurrency: 'COP',
};

export const PAYER_SIDEBAR_PROFILES: PayerSidebarProfile[] = [
    {
        id: 'ars-primera',
        category: 'EPS • SALUD',
        name: 'ARS Primera',
        status: 'ACTIVE',
        bindsRealPayload: true,
        footerLabel: 'Expires: Dec 2024',
        footerIcon: 'calendar_today',
        agreementGeneral: { ...AGREEMENT_GENERAL_DEMO },
        agreementDocuments: { ...AGREEMENT_DOCUMENTS_DEMO, relatedFiles: [...AGREEMENT_DOCUMENTS_DEMO.relatedFiles] },
        demoTariffPayload: {},
    },
    {
        id: 'sura-arl',
        category: 'ARL • RIESGOS',
        name: 'Sura ARL Nacional',
        status: 'DRAFT',
        bindsRealPayload: false,
        footerLabel: 'Last edit: 2d ago',
        footerIcon: 'edit_document',
        agreementGeneral: SURa_GENERAL,
        agreementDocuments: {
            primaryDocument: {
                title: 'Borrador convenio ARL',
                status: 'Draft',
                contractId: SURa_GENERAL.contractId,
                expiresAt: SURa_GENERAL.effectiveTo,
                repositoryId: DEMO_CONTRACT_DOCUMENT.repositoryId,
                repositoryNodeId: DEMO_CONTRACT_DOCUMENT.repositoryNodeId,
                mimeType: DEMO_CONTRACT_DOCUMENT.mimeType,
            },
            relatedFiles: [
                {
                    id: 'sura-annex-1',
                    title: 'Anexo tarifas SOAT',
                    category: 'TECHNICAL_ANNEXES',
                    sizeLabel: '1.1 MB',
                    updatedAt: '2024-08-20',
                },
            ],
            historicalVersions: [],
        },
        demoTariffPayload: {
            contractId: SURa_GENERAL.contractId,
            payer: SURa_GENERAL.payer,
            provider: SURa_GENERAL.providerName,
            currency: 'COP',
            defaultAllowedVariancePercentage: 8,
            tariffRules: [
                {
                    serviceCode: '890201',
                    procedureCode: '890201',
                    description: 'Consulta medicina general',
                    expectedAmount: 145200,
                    minAmount: 138000,
                    maxAmount: 152000,
                    requiresAuthorization: false,
                },
                {
                    serviceCode: '903895',
                    procedureCode: '903895',
                    description: 'Radiografía simple',
                    expectedAmount: 98000,
                    minAmount: 90000,
                    maxAmount: 105000,
                    requiresAuthorization: true,
                },
            ],
        },
    },
    {
        id: 'nueva-eps',
        category: 'EPS • SALUD',
        name: 'Nueva EPS Integral',
        status: 'ACTIVE',
        bindsRealPayload: false,
        footerLabel: 'Expires: Jun 2025',
        footerIcon: 'calendar_today',
        agreementGeneral: NUEVA_EPS_GENERAL,
        agreementDocuments: {
            primaryDocument: {
                title: 'Contrato marco Nueva EPS',
                status: 'Active',
                contractId: NUEVA_EPS_GENERAL.contractId,
                expiresAt: NUEVA_EPS_GENERAL.effectiveTo,
                repositoryId: DEMO_CONTRACT_DOCUMENT.repositoryId,
                repositoryNodeId: DEMO_CONTRACT_DOCUMENT.repositoryNodeId,
                mimeType: DEMO_CONTRACT_DOCUMENT.mimeType,
            },
            relatedFiles: [
                {
                    id: 'neps-annex-1',
                    title: 'Manual tarifario ISS 2024',
                    category: 'TECHNICAL_ANNEXES',
                    sizeLabel: '3.2 MB',
                    updatedAt: '2024-07-10',
                },
            ],
            historicalVersions: [{ id: 'neps-hist-1', title: 'Convenio 2023', archivedAt: '2023-12-01' }],
        },
        demoTariffPayload: {
            contractId: NUEVA_EPS_GENERAL.contractId,
            payer: NUEVA_EPS_GENERAL.payer,
            provider: NUEVA_EPS_GENERAL.providerName,
            currency: 'COP',
            defaultAllowedVariancePercentage: 10,
            tariffRules: [
                {
                    serviceCode: '890301',
                    procedureCode: '890301',
                    description: 'Consulta especializada',
                    expectedAmount: 210000,
                    minAmount: 195000,
                    maxAmount: 225000,
                    requiresAuthorization: false,
                },
                {
                    serviceCode: '907106',
                    procedureCode: '907106',
                    description: 'Hemograma completo',
                    expectedAmount: 42000,
                    minAmount: 38000,
                    maxAmount: 46000,
                    requiresAuthorization: false,
                },
                {
                    serviceCode: '890208',
                    procedureCode: '890208',
                    description: 'Panel metabólico',
                    expectedAmount: 105000,
                    minAmount: 95000,
                    maxAmount: 115000,
                    requiresAuthorization: true,
                },
            ],
        },
    },
];
